#!/bin/bash

s01=101-rpg

s01() {
	chmc $s01
	
	alias  s0='export pos="-90 75 274"    && echo pos=sita出生點0'
	alias  s1='export pos="-83 80 247"    && echo pos=sita出生點sandstone'
	alias  s2='export pos="-71 87 216"    && echo pos=qq家'
}

alias 01=s01
