#!/bin/bash
###
. /home/sita/script/include/console.color
. /home/sita/script/include/persistent

###
gandi=/home/sita/script/mis/dns.gandi.yozliu.pw.sh
RECORD=r53

###
my_ip_address() {
    curl -s4 http://me.gandi.net
}

###
start() {
    echo Starting $(basename $0) ...
    gandi_append
}

gandi_append() {
    ip=$(my_ip_address)
    echo -e ${GREEN}== Appending ${YELLOW}$RECORD.yozliu.pw IN A "$ip" ... ${NC}
    $gandi append $RECORD $ip
    # $gandi query $RECORD
}

stop() {
    echo Stopping $(basename $0) ...
    gandi_remove
}

gandi_remove() {
    ip=$(my_ip_address)
    echo -e ${GREEN}== Removing ${YELLOW}$RECORD.yozliu.pw IN A "$ip" ... ${NC}
    $gandi remove $RECORD $ip
    # $gandi query $RECORD
}

###
case "$1" in
  start)
    start
    exit
    ;;
  stop)
    stop
    exit
    ;;
  *)
    start
esac
