#!/bin/bash
###
. /home/sita/script/include/console.color
. /home/sita/script/include/persistent

###
# gandi=/home/sita/script/mis/dns.gandi.yozliu.pw.sh
gandi=/home/sita/script/mis/dns.gandi.creeper.tw.sh
RECORD=r53

###
ighost=$(hostname | grep -E "(-[0-9a-z]{4})")

###
my_ip_address() {
    curl -s4 http://me.gandi.net
}

###
start() {
    echo DNS Appending: $(basename $0)
    gandi_append
}

gandi_append() {
    ip=$(my_ip_address)
    echo -e ${GREEN}== Appending ${YELLOW}$RECORD.yozliu.pw IN A "$ip" ... ${NC}
    $gandi append $RECORD $ip
    # $gandi query $RECORD
}

stop() {
    echo DNS Removing: $(basename $0)
    gandi_remove
}

gandi_remove() {
    ip=$(my_ip_address)
    echo -e ${GREEN}== Removing ${YELLOW}$RECORD.yozliu.pw IN A "$ip" ... ${NC}
    $gandi remove $RECORD $ip
    # $gandi query $RECORD
}

###
DIR=$(readlink -e "$0")
DP0=$(dirname "$DIR")
[ -z "$ighost" ] && $DP0/bchome $1
[ ! -z "$ighost" ] && $DP0/bcgroups $1

###
case "$1" in
  start)
    start
    gandi_start
    exit
    ;;
  stop)
    stop
    gandi_stop
    exit
    ;;
  *)
    start
    gandi_start
esac
