#!/bin/bash

#=================================
. /home/sita/script/include/console.color

#=================================
gandi=/home/sita/script/mis/dns.gandi.yozliu.pw.sh
RECORD=r53

#=================================
addto_crontab() {
	(crontab -l; echo "$*") | crontab -
}

delfrom_crontab() {
	line=$*
	line=$(echo "$line" | sed 's/\//\\\//g')
	crontab -l | sed "/$line/d" | crontab -
}

#=================================
lookup_dns_ip() {
  host "$1" | sed -rn 's@^.* has address @@p'
}

#=================================
my_ip_address() {
    curl -s4 http://me.gandi.net
}

#=================================
start() {
    echo DNS Groups: $(basename $0)
	
	# echo -e Collecting ip: ${GREEN}"localhost"${NC}
	# bcip+=$(my_ip_address)
	# bcip+=" "
	
	echo -e Collecting ip: ${GREEN}"bc.creeper.tw"${NC}
	bcip+=$(lookup_dns_ip bc.creeper.tw)
	bcip+=" "
	
	echo -e Collecting ip: ${GREEN}"gem.creeper.tw"${NC}
	bcip+=$(lookup_dns_ip gem.creeper.tw)
	bcip+=" "

	# echo -e Collecting ip: ${GREEN}"chsliu@gmail.com"${NC}
	# bcip+=$(gcloud --account "chsliu@gmail.com" --project "creeper-196707" compute instances list | grep RUNNING | grep -E "(-[0-9a-z]{4})\b" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep -v '10.1')
	# bcip+=" "

	# echo -e Collecting ip: ${GREEN}"sita@changen.com.tw"${NC}
	# bcip+=$(gcloud --account "sita@changen.com.tw" --project "creeper-199909" compute instances list | grep RUNNING | grep -E "(-[0-9a-z]{4})\b" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep -v '10.1')
	# bcip+=" "

	# echo -e Collecting ip: ${GREEN}"creeper.workshop@gmail.com"${NC}
	# bcip+=$(gcloud --account "creeper.workshop@gmail.com" --project "creeperworkshop-web" compute instances list | grep RUNNING | grep -E "(-[0-9a-z]{4})\b" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep -v '10.1')
	# bcip+=" "

	
	bcip=$(echo $bcip|tr ' ' '\n'|sort -u)
	echo -e bcip: ${GREEN}$bcip${NC}

	$gandi set $RECORD $bcip
}

#=================================
stop() {
    echo DNS Removing: $(basename $0)
}

#=================================
case "$1" in
  install)
    delfrom_crontab "$(basename $0)"
	addto_crontab "#gcloud DNS update $(basename $0)"
    addto_crontab "10 6 * * * /bin/bash $(readlink -e $0)"
    exit
    ;;
  remove)
    delfrom_crontab "$(basename $0)"
    exit
    ;;
  start)
    start
    exit
    ;;
  stop)
    stop
    exit
    ;;
  *)
    start
esac
