#!/bin/bash

. /home/sita/script/include/common_helper
. /home/sita/script/include/console.color
. /home/sita/script/include/gcloud_helper

###
dnsupdate=/home/sita/script/mis/gcloud.dns.update.sh
gandi=/home/sita/script/mis/dns.gandi.creeper.tw.sh

###
default_account=$(get_account)

###
# dns_account=chsliu@gmail.com
# dns_project=creeper-196707

###
dns_account=sita@changen.com.tw
dns_project=creeper-199909

### 
addto_crontab() {
	(crontab -l; echo "$*") | crontab -
}

delfrom_crontab() {
	line=$*
	line=$(echo "$line" | sed 's/\//\\\//g')
	crontab -l | sed "/$line/d" | crontab -
}

my_ip_address() {
    curl -s4 http://me.gandi.net
}

###
HOST=$(basename $0)

start() {
    echo Starting $(basename $0) ...
}

gandi_start() {
    ip=$(my_ip_address)
    echo -e ${GREEN}== Set ${YELLOW}$HOST.creeper.tw IN A "$ip" ... ${NC}
    $gandi set $HOST $ip
}

stop() {
    echo Stopping $(basename $0) ...
}

gandi_stop() {
    echo Gandi Stopping $(basename $0) ...
}

###
case "$1" in
  install)
    delfrom_crontab "$(basename $0)"
	addto_crontab "#gcloud DNS update $(basename $0)"
    addto_crontab "10 6 * * * /bin/bash $(readlink -e $0)"
    exit
    ;;
  remove)
    delfrom_crontab "$(basename $0)"
    exit
    ;;
  start)
    start
	# gandi_start
    exit
    ;;
  stop)
    stop
	# gandi_stop
    exit
    ;;
  *)
    start
	# gandi_start
esac
