#!/bin/bash

. /home/sita/script/include/console.color

### 
addto_crontab() {
	(crontab -l; echo "$*") | crontab -
}

delfrom_crontab() {
	line=$*
	line=$(echo "$line" | sed 's/\//\\\//g')
	crontab -l | sed "/$line/d" | crontab -
}

###
HOST=$(basename $0)

start() {
    # DNS transaction start
    echo -e ${YELLOW}=== Starting DNS Changes: $HOST.creeper.tw ${NC}
    /home/sita/script/mis/gcloud.dns.update.sh start creeper-196707 creeper-tw

    # A www.creeper.tw 1hour
    echo -e ${GREEN}=== Updating A $HOST.creeper.tw 3hour ${NC}
    /home/sita/script/mis/gcloud.dns.update.sh A creeper-tw $HOST creeper.tw 3hour 3hour

    # DNS transaction commit
    echo -e ${YELLOW}=== Commiting DNS Changes: $HOST.creeper.tw ${NC}
    /home/sita/script/mis/gcloud.dns.update.sh commit creeper-196707 creeper-tw
}

stop() {
    echo Stopping $(basename $0) ...
}

###
case "$1" in
  install)
	addto_crontab "#gcloud DNS update $(basename $0)"
    addto_crontab "10 6 * * * /bin/bash $(readlink -e $0)"
    exit
    ;;
  remove)
    delfrom_crontab "$(basename $0)"
    exit
    ;;
  start)
    start
    exit
    ;;
  stop)
    stop
    exit
    ;;
  *)
    start
esac
