#!/bin/bash

. /home/sita/script/include/common_helper
. /home/sita/script/include/console.color
. /home/sita/script/include/gcloud_helper

###
dnsupdate=/home/sita/script/mis/gcloud.dns.update.sh

###
default_account=$(get_account)

###
# dns_account=chsliu@gmail.com
# dns_project=creeper-196707

###
dns_account=sita@changen.com.tw
dns_project=creeper-199909

### 
addto_crontab() {
	(crontab -l; echo "$*") | crontab -
}

delfrom_crontab() {
	line=$*
	line=$(echo "$line" | sed 's/\//\\\//g')
	crontab -l | sed "/$line/d" | crontab -
}

###
HOST=$(basename $0)

start() {
	echo -e ${GREEN}=========================${NC}
    set_account $dns_account
    
    # DNS transaction start
    echo -e ${GREEN}=== Starting DNS Changes: ${YELLOW}$HOST.creeper.tw ${NC}
    $dnsupdate start $dns_project creeper-tw

    # A www.creeper.tw 1hour
    echo -e ${GREEN}== Updating ${YELLOW}$HOST.creeper.tw 3hour IN A ... ${NC}
    $dnsupdate A creeper-tw $HOST creeper.tw 3hour 3hour

    # DNS transaction commit
    echo -e ${GREEN}=== Commiting DNS Changes: ${YELLOW}$HOST.creeper.tw ${NC}
    $dnsupdate commit $dns_project creeper-tw
    
	echo -e ${GREEN}=========================${NC}
    
    # DNS transaction start
    echo -e ${GREEN}=== Starting DNS Changes: ${YELLOW}$HOST.creeperworkshop.tw ${NC}
    $dnsupdate start $dns_project creeperworkshop-tw

    # A creeperworkshop.tw 1hour
    echo -e ${GREEN}== Updating ${YELLOW}creeperworkshop.tw 3hour IN A ... ${NC}
    $dnsupdate A creeperworkshop-tw @ creeperworkshop.tw 3hour 3hour

    # A file.creeperworkshop.tw 1hour
    echo -e ${GREEN}== Updating ${YELLOW}file.creeperworkshop.tw 3hour IN A ... ${NC}
    $dnsupdate A creeperworkshop-tw file creeperworkshop.tw 3hour 3hour

    # DNS transaction commit
    echo -e ${GREEN}=== Commiting DNS Changes: ${YELLOW}$HOST.creeperworkshop.tw ${NC}
    $dnsupdate commit $dns_project creeperworkshop-tw
	
    set_account $default_account
	echo -e ${GREEN}=========================${NC}
}

stop() {
    echo Stopping $(basename $0) ...
}

###
case "$1" in
  install)
    delfrom_crontab "$(basename $0)"
	addto_crontab "#gcloud DNS update $(basename $0)"
    addto_crontab "10 6 * * * /bin/bash $(readlink -e $0)"
    exit
    ;;
  remove)
    delfrom_crontab "$(basename $0)"
    exit
    ;;
  start)
    start
    exit
    ;;
  stop)
    stop
    exit
    ;;
  *)
    start
esac
