#!/bin/bash
#!/bin/bash -x

#=================================
. /home/sita/script/include/common_helper
. /home/sita/script/include/console.color
. /home/sita/script/include/gcloud_helper
. /home/sita/script/include/persistent

###
dnsupdate=/home/sita/script/mis/gcloud.dns.update.sh
# gandi=/home/sita/script/mis/dns.gandi.yozliu.pw.sh
gandi=/home/sita/script/mis/dns.gandi.creeper.tw.sh
RECORD=r53
DOMAIN=creeper.tw
# DNSTOCHECK1="mc.creeper.tw"
# DNSTOCHECK1="gem.creeper.tw"
# DNSTOCHECK2="r53.yozliu.pw"

###
default_account=$(get_account)

###
# dns_account=chsliu@gmail.com
# dns_project=creeper-196707

###
dns_account=sita@changen.com.tw
dns_project=creeper-199909

### 
addto_crontab() {
	(crontab -l; echo "$*") | crontab -
}

lookup_dns_ip() {
    host "$1" | sed -rn 's@^.* has address @@p'
}

delfrom_crontab() {
	line=$*
	line=$(echo "$line" | sed 's/\//\\\//g')
	crontab -l | sed "/$line/d" | crontab -
}

# is_tp_already_set() {
    # dnsip=$(lookup_dns_ip mc.creeper.tw)
    # dnsip=$(lookup_dns_ip $DNSTOCHECK1)
    # myip=$(curl -s https://api.ipify.org)
    # myip=$(my_ip_address)
    # Checking if Load Balancer already started
    # echo -e ${YELLOW}=== DNS Status: ${GREEN}DNS=$dnsip,IP=$myip ${NC}
    # [ -z "$dnsip" ] && return 1
	# echo dnsip=$dnsip
	# echo myip=$myip
    [ "$dnsip" == "$myip" ]
    # return $?
# }

# is_tp_already_set() {
    # dnsip=$(lookup_dns_ip $DNSTOCHECK1)
    # myip=$(my_ip_address)
    # [ -z "$dnsip" ] && return 1
    # [ "$dnsip" == "$myip" ]
    # return $?
# }

my_ip_address() {
    curl -s4 http://me.gandi.net
}

# is_tp_already_set_2() {
	# echo test if $DNSTOCHECK2 has $(my_ip_address)
	# lookup_dns_ip $DNSTOCHECK2 | grep -F --quiet "$(my_ip_address)"
	# return $?
# }

is_dns_already_set() {
	# echo test if $DNSTOCHECK2 has $(my_ip_address)
	lookup_dns_ip $1 | grep -F --quiet "$(my_ip_address)"
	return $?
}

###
# DBFILE=~/.db/dnsdb.txt
# HOST=$(basename $0)
num=$(cat /dev/urandom | tr -dc '0-9' | fold -w 256 | head -n 1 | head --bytes 1)
# num=$(cat /dev/urandom | tr -dc 'a-z' | fold -w 4 | head -n 1)
HOST=tp$num

start() {
    # is_tp_already_set && return
    is_dns_already_set gem.creeper.tw && echo -e ${YELLOW}=== start abort ... ${NC} && return

    # bungee_restart
    
	# declare -A dnsdb
    # [ -f $DBFILE ] && source $DBFILE
	eval "$(dbload 'dnsdb')"
	LAST=${dnsdb[$(basename $0)]}
	
	echo -e ${GREEN}=========================${NC}
    set_account $dns_account
    
    # DNS transaction start
    echo -e ${GREEN}=== Starting DNS Changes: ${YELLOW}$HOST.creeper.tw ${NC}
    $dnsupdate start $dns_project creeper-tw

    if [ $(date +%H) == '06' ]; then
        # On 6am
        # del A r53.creeper.tw 3hour 1min
        echo -e ${GREEN}== Deleting ${YELLOW}r53.creeper.tw 1min IN A ... ${NC}
        $dnsupdate del $dns_project creeper-tw r53 creeper.tw 3hour 1min A
    fi

    if [ $(date +%w) == 6 ]; then
        
        [ ! -z "$LAST" ] && echo -e ${GREEN}== Deleting ${YELLOW}$LAST.creeper.tw ${GREEN}3hour to ${YELLOW}1min IN A ... ${NC}
        [ ! -z "$LAST" ] && $dnsupdate del $dns_project creeper-tw $LAST creeper.tw 3hour 1min A
		
        # On Saturday
        # A tp1.creeper.tw 1min
        echo -e ${GREEN}== Updating ${YELLOW}$HOST.creeper.tw ${GREEN}3hour to ${YELLOW}1min IN A ... ${NC}
        $dnsupdate A creeper-tw $HOST creeper.tw 3hour 1min
		
        # A gem.creeper.tw 1min
        echo -e ${GREEN}== Updating ${YELLOW}gem.creeper.tw ${GREEN}3hour to ${YELLOW}1min IN A ... ${NC}
        $dnsupdate A creeper-tw gem creeper.tw 3hour 1min
		
        # A db.creeper.tw 1min
        echo -e ${GREEN}== Updating ${YELLOW}db.creeper.tw ${GREEN}3hour to ${YELLOW}1min IN A ... ${NC}
        $dnsupdate A creeper-tw db creeper.tw 3hour 1min
        
        # CNAME mc.creeper.tw = tp1.creeper.tw 1min
        # echo -e ${GREEN}== Updating ${YELLOW}mc.creeper.tw ${GREEN}3hour to ${YELLOW}1min IN CNAME $HOST.creeper.tw ${NC}
        # $dnsupdate CNAME creeper-tw mc creeper.tw $HOST.creeper.tw. 3hour 1min
        
        # A wiki.creeper.tw 1min
        echo -e ${GREEN}== Updating ${YELLOW}wiki.creeper.tw ${GREEN}3hour to ${YELLOW}1min IN A ... ${NC}
        $dnsupdate A creeper-tw wiki creeper.tw 3hour 1min

        # append A r53.creeper.tw 1min
        # echo -e ${GREEN}=== Appending A r53.creeper.tw 1min ${NC}
        # $dnsupdate append $dns_project creeper-tw r53 creeper.tw 3hour 1min A

        # A redis.creeper.tw 1hour
        echo -e ${GREEN}== Updating ${YELLOW}redis.creeper.tw 3hour IN A ... ${NC}
        $dnsupdate A creeper-tw redis creeper.tw 3hour 1min
    
    else
        
        [ ! -z "$LAST" ] && echo -e ${GREEN}== Deleting ${YELLOW}$LAST.creeper.tw ${GREEN}3hour to ${YELLOW}1min IN A ... ${NC}
        [ ! -z "$LAST" ] && $dnsupdate del $dns_project creeper-tw $LAST creeper.tw 3hour 1min A
		
        # Not Saturday
        # A tp1.creeper.tw 3hour
        echo -e ${GREEN}== Updating ${YELLOW}$HOST.creeper.tw ${GREEN}1min to ${YELLOW}3hour IN A ... ${NC}
        $dnsupdate A creeper-tw $HOST creeper.tw 1min 3hour
        
        # A gem.creeper.tw 3hour
        echo -e ${GREEN}== Updating ${YELLOW}gem.creeper.tw ${GREEN}1min to ${YELLOW}3hour IN A ... ${NC}
        $dnsupdate A creeper-tw gem creeper.tw 1min 3hour
        
        # A db.creeper.tw 3hour
        echo -e ${GREEN}== Updating ${YELLOW}db.creeper.tw ${GREEN}1min to ${YELLOW}3hour IN A ... ${NC}
        $dnsupdate A creeper-tw db creeper.tw 1min 3hour
        
        # CNAME mc.creeper.tw = tp1.creeper.tw 3hour
        # echo -e ${GREEN}== Updating ${YELLOW}mc.creeper.tw ${GREEN}1min to ${YELLOW}3hour IN CNAME $HOST.creeper.tw ${NC}
        # $dnsupdate CNAME creeper-tw mc creeper.tw $HOST.creeper.tw. 1min 3hour
        
        # A wiki.creeper.tw 1min
        echo -e ${GREEN}== Updating ${YELLOW}wiki.creeper.tw ${GREEN}1min to ${YELLOW}3hour IN A ... ${NC}
        $dnsupdate A creeper-tw wiki creeper.tw 1min 3hour     
        
        # A r53.creeper.tw 3hour
        # echo -e ${GREEN}=== Appending A r53.creeper.tw 3hour ${NC}
        # $dnsupdate A creeper-tw r53 creeper.tw 1min 3hour

        # A redis.creeper.tw 1hour
        echo -e ${GREEN}== Updating ${YELLOW}redis.creeper.tw 3hour IN A ... ${NC}
        $dnsupdate A creeper-tw redis creeper.tw 1min 3hour
    fi

    # DNS transaction commit
    echo -e ${GREEN}=== Commiting DNS Changes: ${YELLOW}$HOST.creeper.tw ${NC}
    $dnsupdate commit $dns_project creeper-tw
    
    set_account $default_account
	echo -e ${GREEN}=========================${NC}
	
	dnsdb[$(basename $0)]=$HOST
    # [ ! -z "${!dnsdb[*]}" ] && declare -p dnsdb >$DBFILE
	[ ! -z "${!dnsdb[*]}" ] && dbsave "dnsdb" "$(declare -p dnsdb)"
}

start2() {
    # is_tp_already_set && return
    is_dns_already_set gem.creeper.tw && echo -e ${YELLOW}=== start2 abort ... ${NC} && return
    
	echo -e ${GREEN}=========================${NC}
    set_account $dns_account
    
    # DNS transaction start
    echo -e ${GREEN}=== Starting DNS Changes: ${YELLOW}home.changen.com.tw ${NC}
    $dnsupdate start $dns_project changen-com-tw

    if [ $(date +%w) == 6 ]; then
        # On Saturday
        # A home.changen.com.tw 1min
        echo -e ${GREEN}== Updating ${YELLOW}home.changen.com.tw ${GREEN}3hour to ${YELLOW}1min IN A ...${NC}
        $dnsupdate A changen-com-tw home changen.com.tw 3hour 1min
    else
        # Not Saturday
        # A home.changen.com.tw 3hour
        echo -e ${GREEN}= Updating ${YELLOW}home.changen.com.tw ${GREEN}1min to ${YELLOW}3hour IN A ... ${NC}
        $dnsupdate A changen-com-tw home changen.com.tw 1min 3hour
    fi

    # DNS transaction commit
    echo -e ${GREEN}=== Commiting DNS Changes: ${YELLOW}home.changen.com.tw ${NC}
    $dnsupdate commit $dns_project changen-com-tw
    
    set_account $default_account
	echo -e ${GREEN}=========================${NC}
}

bungee_restart() {
    # is_tp_already_set && return
    is_dns_already_set gem.creeper.tw && echo -e ${YELLOW}=== bungee_restart abort ... ${NC} && return
	
	. /home/sita/script/minecraft/alias.minecraft
	
	s65
	mcserver halt
	[ -f update.sh ] && echo -e "${GREEN}=== Updating $mcver/update.sh ${NC}" && as_user "./update.sh"
	server.prep
	mcserver start
}

gandi_append() {
    # is_tp_already_set_2 && return
    is_dns_already_set $RECORD.$DOMAIN && echo -e ${YELLOW}=== gandi_append abort ... ${NC} && return
    
	# echo $DNSTOCHECK2 doesn not have $(my_ip_address)
	
	eval "$(dbload 'bc')"
	LAST=${bc[$(basename $0)]}
    
    ip=$(my_ip_address)
    [ "$LAST" == "$ip" ] && return 
    
    [ ! -z "$LAST" ] && echo -e ${GREEN}== Removing ${YELLOW}$RECORD.$DOMAIN IN A "$LAST" ... ${NC}
    [ ! -z "$LAST" ] && $gandi remove $RECORD $LAST
    
    $gandi append $RECORD $ip
    
	bc[$(basename $0)]=$ip
	[ ! -z "${!bc[*]}" ] && dbsave "bc" "$(declare -p bc)"
}

gandi_start() {
    is_dns_already_set gem.creeper.tw && echo -e ${YELLOW}=== gandi_start abort ... ${NC} && return
	
    ip=$(my_ip_address)
	
    # echo -e ${GREEN}== Set ${YELLOW}$HOST.creeper.tw IN A "$ip" ... ${NC}
    # $gandi set $HOST $ip
	
    echo -e ${GREEN}== Set ${YELLOW}gem.creeper.tw IN A "$ip" ... ${NC}
    $gandi set gem $ip
	
    echo -e ${GREEN}== Set ${YELLOW}wiki.creeper.tw IN A "$ip" ... ${NC}
    $gandi set wiki $ip
	
    echo -e ${GREEN}== Set ${YELLOW}db.creeper.tw IN A "$ip" ... ${NC}
    $gandi set db $ip
	
    echo -e ${GREEN}== Set ${YELLOW}redis.creeper.tw IN A "$ip" ... ${NC}
    $gandi set redis $ip
}

stop() {
    echo Stopping $(basename $0) ...
}

gandi_remove() {
    echo Gandi Removing $RECORD.creeper.tw ...
    $gandi remove $RECORD $(my_ip_address)
}

gandi_stop() {
    echo Gandi Stopping $(basename $0) ...
}

###
case "$1" in
  install)
    delfrom_crontab "$(basename $0)"
	addto_crontab "#gcloud DNS update $(basename $0)"
    addto_crontab "5 6 * * * /bin/bash $(readlink -e $0)"
    exit
    ;;
  remove)
    delfrom_crontab "$(basename $0)"
    exit
    ;;
  start)
    # start
	bungee_restart
    start2
    gandi_append
    gandi_start
    exit
    ;;
  stop)
    # stop
    gandi_remove
    gandi_stop
    exit
    ;;
  test)
    # bungee_restart
    exit
    ;;
  *)
    # start
	bungee_restart
    start2
    gandi_append
    gandi_start
esac
