#!/bin/bash

. /home/sita/script/include/console.color

### 
addto_crontab() {
	(crontab -l; echo "$*") | crontab -
}

delfrom_crontab() {
	line=$*
	line=$(echo "$line" | sed 's/\//\\\//g')
	crontab -l | sed "/$line/d" | crontab -
}

###
start() {
    HOST=$(basename $0)
    # HOST=$(hostname)
    bchost="bungeecord-tw2"

    # DNS transaction start
    echo -e ${YELLOW}=== Starting DNS Changes: $(basename $0).creeper.tw ${NC}
    /home/sita/script/mis/gcloud.dns.update.sh start creeper-196707 creeper-tw

    if [ $(date +%w) == 6 ]; then
        if [ $(hostname) == $bchost ]; then
            # A tw2.creeper.tw 1min
            echo -e ${GREEN}=== Updating A $HOST.creeper.tw 1min ${NC}
            /home/sita/script/mis/gcloud.dns.update.sh A creeper-tw $HOST creeper.tw 3hour 1min
            
            # CNAME mc.creeper.tw = tw2.creeper.tw 1min
            echo -e ${GREEN}=== Updating CNAME mc.creeper.tw = $HOST.creeper.tw 3hour to 1min ${NC}
            /home/sita/script/mis/gcloud.dns.update.sh CNAME creeper-tw mc creeper.tw $HOST.creeper.tw. 3hour 1min
        else
            # CNAME mc.creeper.tw = lb.creeper.tw 1min
            echo -e ${GREEN}=== Updating CNAME mc.creeper.tw = lb.creeper.tw 3hour to 1min ${NC}
            /home/sita/script/mis/gcloud.dns.update.sh CNAME creeper-tw mc creeper.tw lb.creeper.tw. 3hour 1min
        fi

        # append A r53.creeper.tw 1min
        echo -e ${GREEN}=== Appending A r53.creeper.tw 1min ${NC}
        /home/sita/script/mis/gcloud.dns.update.sh append creeper-196707 creeper-tw r53 creeper.tw 3hour 1min A
    else
        if [ $(hostname) == $bchost ]; then
            # A tw2.creeper.tw 3hour
            echo -e ${GREEN}=== Updating A $HOST.creeper.tw 3hour ${NC}
            /home/sita/script/mis/gcloud.dns.update.sh A creeper-tw $HOST creeper.tw 1min 3hour
            
            # CNAME mc.creeper.tw = tw2.creeper.tw 3hour
            echo -e ${GREEN}=== Updating CNAME mc.creeper.tw = $HOST.creeper.tw 1min to 3hour ${NC}
            /home/sita/script/mis/gcloud.dns.update.sh CNAME creeper-tw mc creeper.tw $HOST.creeper.tw. 1min 3hour
        else
            # CNAME mc.creeper.tw = lb.creeper.tw 3hour
            echo -e ${GREEN}=== Updating CNAME mc.creeper.tw = lb.creeper.tw 1min to 3hour ${NC}
            /home/sita/script/mis/gcloud.dns.update.sh CNAME creeper-tw mc creeper.tw lb.creeper.tw. 1min 3hour
        fi
        
        # append A r53.creeper.tw 3hour
        echo -e ${GREEN}=== Appending A r53.creeper.tw 3hour ${NC}
        /home/sita/script/mis/gcloud.dns.update.sh append creeper-196707 creeper-tw r53 creeper.tw 1min 3hour A
    fi

    # DNS transaction commit
    echo -e ${YELLOW}=== Commiting DNS Changes: $(basename $0).creeper.tw ${NC}
    /home/sita/script/mis/gcloud.dns.update.sh commit creeper-196707 creeper-tw
}

stop() {
    echo $(basename $0) stopping ...
}

###
case "$1" in
  install)
	addto_crontab "#gcloud DNS update $(basename $0)"
    addto_crontab "10 6 * * * /bin/bash $(readlink -e $0)"
    exit
    ;;
  remove)
    delfrom_crontab "$(basename $0)"
    exit
    ;;
  start)
    start
    exit
    ;;
  stop)
    stop
    exit
    ;;
  *)
    start
esac
