#!/bin/bash

. /home/sita/script/include/console.color

### 
addto_crontab() {
	(crontab -l; echo "$*") | crontab -
}

delfrom_crontab() {
	line=$*
	line=$(echo "$line" | sed 's/\//\\\//g')
	crontab -l | sed "/$line/d" | crontab -
}

case "$1" in
  install)
	addto_crontab "#gcloud DNS update $(basename $0)"
    addto_crontab "10 6 * * * /bin/bash $(readlink -e $0)"
    exit
    ;;
  remove)
    delfrom_crontab "$(basename $0)"
    exit
    ;;
esac

###
HOST=$(basename $0)

echo -e ${YELLOW}=== Starting DNS Changes: creeper.tw ${NC}
/home/sita/script/mis/gcloud.dns.update.sh start creeper-196707 creeper-tw

echo -e ${GREEN}=== Updating A $HOST.creeper.tw 1hour ${NC}
/home/sita/script/mis/gcloud.dns.update.sh A creeper-tw $HOST creeper.tw 1hour 1hour

echo -e ${GREEN}=== Updating A creeper.tw 1hour ${NC}
/home/sita/script/mis/gcloud.dns.update.sh A creeper-tw @ creeper.tw 1hour 1hour

echo -e ${YELLOW}=== Commiting DNS Changes: creeper.tw ${NC}
/home/sita/script/mis/gcloud.dns.update.sh commit creeper-196707 creeper-tw
