#!/bin/bash
# localpc -> nfs
# localvm -> host nfs
# cloudpc -> gcsfuse

HOST=pve5

nfs_enable() {
	[ -d $3 ] || sudo mkdir $3

	sudo umount $3 &>/dev/null
	sudo mount -t nfs -o nosuid,noexec,nodev,bg,soft $1:$2 $3
	
	alias $1="\"cd /mnt/$1\""
}

nfs_enable $HOST /tank/Shares/Users/yoz/minecraft /mnt
# nfs_enable $HOST /mnt/backup /mnt/backup
