#!/bin/bash

mc1112=forge-1.11.2

func1112() {
	export mcver=$mc1112
	echo mcver=$mcver
	alias  s1='export pos="250 70 250"    && echo pos=家'
	alias  s1a='export pos="207 139 249" && echo pos=船電梯頂端'
	alias  s2='export pos="10455 80 4400" && echo pos=林地'
	alias  s3='export pos="1262 71 1814" && echo pos=終界要塞'
	alias  s4='export pos="-4 62 4" && echo pos=終界返回傳送門'
	alias  s5='export pos="-1224 62 -249" && echo pos=終界城1'
	alias  s6='export pos="2032 65 1696" && echo pos=蘑菇島'
}

alias v11=func1112
