#!/bin/bash

mc1112=forge-1.11.2

func1112() {
	export mcver=$mc1112
	echo mcver=$mcver
	alias  s1='export pos="250 70 250"    && echo pos=家'
	alias  s2='export pos="10455 80 4400" && echo pos=林地'
}

alias v11=func1112
