#!/bin/bash

s65=65-bungeeCord-azure

s65() {
	chmc $s65
}

alias 65=s65
alias probe='65 && mcdo viaversion probe'
# alias ghub='65 && mcdo send all hub'
# alias guhc='65 && mcdo send all uhc'
alias send='65 && mcdo viaversion probe && mcdo sendtoall send all $*'
alias glist='65 && export LOG_DELAY=.5 && mcdo glist showall && export LOG_DELAY=.1'
alias greload='65 && export LOG_DELAY=.5 && mcdo greload && export LOG_DELAY=.1'
