ip_forward: false
network_compression_threshold: 256
stats: 71caa302-444f-46b7-b878-a6bc3f703080
permissions:
  default:
  - bungeecord.command.list
  admin:
  - bungeecord.command.server
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
groups:
  chsliu:
  - admin
servers:
  hub:
    motd: 大廳
    address: lxcmc204:25566
    restricted: false
  # hh:
    # motd: 大廳測試版
    # address: lxcmc210:25566
    # restricted: false
  # sv:
    # motd: Survival
    # address: lxcmc204:25567
    # restricted: false
  mv:
    motd: RPG生存世界
    address: lxcmc204:25568
    restricted: false
  # mw:
    # motd: MultiWorld
    # address: lxcmc204:25569
    # restricted: false
  # fe:
    # motd: ForgeEssentials
    # address: lxcmc204:25570
    # restricted: false
  v10:
    motd: 兩張床世界
    address: lxcmc210:25571
    restricted: false
  # v7:
    # motd: RTM世界
    # address: lxcmc204:25572
    # restricted: false
  v11:
    motd: 原味生存世界
    address: lxcmc210:25573
    restricted: false
  uhc:
    motd: UHC with NCP
    address: lxcmc206:25574
    restricted: false
  uhc2:
    motd: UHC
    address: lxcmc206:25575
    restricted: false
  # wither:
    # motd: 挑戰凋零怪
    # address: lxcmc204:25576
    # restricted: false
  # bed:
    # motd: 床戰PvP
    # address: lxcmc204:25577
    # restricted: false
  # pk2:
    # motd: 跑酷螺旋塔2
    # address: lxcmc204:25578
    # restricted: false
  # h2:
    # motd: 大廳1.8
    # address: lxcmc210:25580
    # restricted: false
  bed1:
    motd: 床戰Kingdoms
    address: lxcmc204:25581
    restricted: false
  uhc3:
    motd: UHCrafted
    address: lxcmc204:25582
    restricted: false
  battle:
    motd: 亡國之戰
    address: lxcmc204:25584
    restricted: false
  # dropper:
    # motd: 逆墜落
    # address: lxcmc204:25585
    # restricted: false
  # class:
    # motd: 職階戰爭1.1
    # address: lxcmc204:25586
    # restricted: false
  class2:
    motd: 職階戰爭II 5.1
    address: lxcmc204:25587
    restricted: false
  siege:
    motd: 殲滅攻城戰Ver4.3
    address: lxcmc204:25588
    restricted: false
  # snow:
    # motd: Snowbound
    # address: lxcmc204:25589
    # restricted: false
  terra:
    motd: Terra Swoop Force - A Noxcrew Map
    address: lxcmc204:25590
    restricted: false
  autouhc:
    motd: UHC練習場
    address: lxcmc206:25591
    restricted: false
  lol:
    motd: 聖殿與邪魔之役v1.5.6
    address: lxcmc204:25592
    restricted: false
  bingo:
    motd: MinecraftBINGOv3_1
    address: lxcmc204:25593
    restricted: false
timeout: 30000
listeners:
- query_port: 25577
  motd: bungee
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  ping_passthrough: true
  priorities:
  - hub
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  force_default_server: false
  forced_hosts:
    sitahome.ddns.net: hub
prevent_proxy_connections: false
online_mode: true
player_limit: -1
disabled_commands:
- disabledcommandhere
log_commands: false
connection_throttle: 1000
