ip_forward: false
network_compression_threshold: 256
stats: 71caa302-444f-46b7-b878-a6bc3f703080
permissions:
  default:
  - bungeecord.command.list
  admin:
  - bungeecord.command.server
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
groups:
  chsliu:
  - admin
servers:
  # hypixel:
    # motd: Hypixel
    # address: mc.hypixel.net
    # restricted: false
  hub:
    motd: 大廳
    address: lxcmc204:25566
    restricted: false
  mv:
    motd: RPG生存世界
    address: lxcmc204:25568
    restricted: false
  v10:
    motd: 兩張床世界
    address: lxcmc210:25571
    restricted: false
  v11:
    motd: 原味生存世界
    address: lxcmc210:25573
    restricted: false
  uhc:
    motd: UHC with NCP
    address: lxcmc206:25574
    restricted: false
  uhc2:
    motd: UHC
    address: lxcmc206:25575
    restricted: false
  bed1:
    motd: 床戰Kingdoms
    address: lxcmc204:25581
    restricted: false
  battle:
    motd: 亡國之戰
    address: lxcmc204:25584
    restricted: false
  siege:
    motd: 殲滅攻城戰Ver4.3
    address: lxcmc204:25588
    restricted: false
  terra:
    motd: Terra Swoop Force - A Noxcrew Map
    address: lxcmc204:25590
    restricted: false
  autouhc:
    motd: UHC練習場
    address: lxcmc206:25591
    restricted: false
  lol:
    motd: 聖殿與邪魔之役v1.5.6
    address: lxcmc204:25592
    restricted: false
  bingo:
    motd: MinecraftBINGOv3_1
    address: lxcmc204:25593
    restricted: false
timeout: 30000
listeners:
- query_port: 25577
  motd: bungee
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  ping_passthrough: true
  priorities:
  - hub
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  force_default_server: false
  forced_hosts:
    sitahome.ddns.net: hub
prevent_proxy_connections: false
player_limit: -1
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 1000
