ip_forward: false
network_compression_threshold: 256
stats: 71caa302-444f-46b7-b878-a6bc3f703080
groups:
  chsliu:
  - admin
servers:
  hub:
    motd: §aCreeper Arena Hub §e1.9/1.10/1.11/1.12 §cUHC and other PvP Games
    address: lxcmc203:25566
    restricted: false
  sv:
    motd: Creeper Arena Survival
    address: lxcminecraft:25567
    restricted: false
  mv:
    motd: Creeper Arena MultiVerse
    address: lxcminecraft:25568
    restricted: false
  mw:
    motd: Creeper Arena MultiWorld
    address: lxcminecraft:25569
    restricted: false
  fe:
    motd: Creeper Arena ForgeEssentials
    address: lxcminecraft:25570
    restricted: false
  v10:
    motd: Two Bed
    address: lxcmc203:25571
    restricted: false
  v7:
    motd: RTM
    address: lxcmc203:25572
    restricted: false
  v11:
    motd: Vanilla
    address: lxcmc203:25573
    restricted: false
  uhc:
    motd: Creeper Arena UHC with NCP
    address: lxcminecraft:25574
    restricted: false
  uhc2:
    motd: Creeper Arena UHC
    address: lxcminecraft:25575
    restricted: false
timeout: 30000
player_limit: -1
listeners:
- query_port: 25577
  motd: |-
    §aCreeper Arena §e1.9/1.10/1.11/1.12
    §cUHC and other PvP Games
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    sitahome.ddns.net: hub
  ping_passthrough: false
  priorities:
  - hub
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 1
  tab_size: 60
  force_default_server: true
prevent_proxy_connections: false
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
