#!/bin/bash

. /home/sita/script/minecraft/alias.minecraft
. /home/sita/script/init.d/start.mc.sh

# dns_external=tw1
dns_external=lobby
dns_updates=($dns_external)
# servers=(s32 s65)
servers=(s65)
servers2=
autostart=1

run $*
