#!/bin/bash

. /home/sita/script/minecraft/alias.minecraft
. /home/sita/script/init.d/start.mc.sh

# dns_external=tw3
dns_external=
# dns_updates=($dns_external bc)
dns_updates=(bcgroups)
servers=(s65)
servers2=
autostart=1
antiddos=1

run $*
