#!/bin/bash

. /home/sita/script/minecraft/alias.minecraft
. /home/sita/script/init.d/start.mc.sh

# dns_external=tw1
# dns_external=lobby
dns_external=
dns_updates=($dns_external bc)
# servers=(s32 s65)
servers=(s65)
#servers=(s31)
servers2=
autostart=1

run $*
