#!/bin/bash

. /home/sita/script/minecraft/alias.minecraft
. /home/sita/script/init.d/start.mc.sh

# dns_external=tw2
dns_external=
# dns_updates=($dns_external bc)
dns_updates=(bcgroups)
#servers=(s32 s65)
servers=(s65)
autostart=1
antiddos=1

run $*
