#!/bin/bash

. /home/sita/script/minecraft/alias.minecraft
. /home/sita/script/init.d/start.mc.sh

dns_external=
dns_updates=($dns_external)
servers=
servers2=

bungee_instance() {
	# dns_updates=(bc)
	dns_updates=(bcgroups)
	servers=(s65)
	autostart=1
	antiddos=1
}

[[ $(hostname) == bungeecord* ]] && bungee_instance
[[ $(hostname) == bc* ]] && bungee_instance

run $*
