#!/bin/bash

###
[ ! -d /tmp/log ] && mkdir /tmp/log
exec > >(tee -i /tmp/$(basename $0).$(date +%F_%T).log)
exec 2>&1

###
runscreen=/home/sita/script/mis/run_in_screen.sh

### 
USERNAME=sita
ME=`whoami`

### 
addto_crontab() {
	(crontab -l; echo "$*") | crontab -
}

delfrom_crontab() {
	line=$*
	line=$(echo "$line" | sed 's/\//\\\//g')
	crontab -l | sed "/$line/d" | crontab -
}

### 
as_user() {
  if [ "$ME" == "$USERNAME" ] ; then
    bash -c "$1"
  else
    su - $USERNAME -c "$1"
  fi
}
