#!/bin/bash

###
[ ! -d /tmp/log ] && mkdir /tmp/log && sudo chown sita:sita /tmp/log
exec > >(tee -a -i /tmp/log/$(basename $0).log)
exec 2>&1

echo 
echo ===================
echo $(date +%F_%T)
echo ===================

###
runscreen=/home/sita/script/mis/run_in_screen.sh

### 
USERNAME=sita
ME=`whoami`

### 
addto_crontab() {
	(crontab -l; echo "$*") | crontab -
}

delfrom_crontab() {
	line=$*
	line=$(echo "$line" | sed 's/\//\\\//g')
	crontab -l | sed "/$line/d" | crontab -
}

### 
as_user() {
  if [ "$ME" == "$USERNAME" ] ; then
    bash -c "$1"
  else
    su - $USERNAME -c "$1"
  fi
}

### 
logconf=/etc/logrotate.d/$(basename $0).logrotate

logrotate_conf() {
    logfile=/tmp/log/$(basename $0).log
    templogconf=/tmp/$(basename $0).logrotate
    
    echo "# $logfile"                    >$templogconf
    echo "# sudo chown root $logconf"   >>$templogconf
    echo "# sudo logrotate -d $logconf" >>$templogconf
    echo /tmp/log/$(basename $0).log {  >>$templogconf
    echo   daily                        >>$templogconf
    echo   dateext                      >>$templogconf
    echo   missingok                    >>$templogconf
    echo   rotate 7                     >>$templogconf
    echo   compress                     >>$templogconf
    echo   delaycompress                >>$templogconf
    echo   notifempty                   >>$templogconf
    echo   copytruncate                 >>$templogconf
    echo }                              >>$templogconf
    
    sudo chown root $templogconf
    sudo mv $templogconf /etc/logrotate.d/
}

logrotate() {
    [ ! -f $logconf ] && logrotate_conf
    sudo logrotate -f $logconf
}

