#!/bin/bash

###
dnsupdate=/home/sita/script/mis/gcloud.dns.update.sh
[ -z "$igctrl" ] && export igctrl=/home/sita/script/minecraft/gcloud/igroup.sh

###
# [ -z "$dns_account" ] && export dns_account=chsliu@gmail.com
# [ -z "$lb_account" ] && export lb_account=sita@changen.com.tw
# [ -z "$ig_account" ] && export ig_account=sita@changen.com.tw
# [ -z "$PROJECT" ] && export PROJECT=creeper-199909
# [ -z "$REGION" ] && export REGION=asia-east1

###
get_account() {
    gcloud config get-value account
}

###
set_account() {
    if [ "$(get_account)" != "$1" ]; then
        # Switching Account
        echo -e ${GREEN}=== Switching to Account: ${YELLOW}$1 ${NC}
        [ ! -z "$1" ] && gcloud config set account $1
    fi
}
