#!/bin/bash

#=================================
DBPATH=~/.db
[ ! -d $DBPATH ] && mkdir $DBPATH

#=================================
dbload() {
	dbfile=$DBPATH/$1.txt
    [ -f $dbfile ] && cat $dbfile
}

#=================================
dbsave() {
	dbfile=$DBPATH/$1.txt
	shift 1
    echo "$*" >$dbfile
}

#=================================
string_hash() {
	str=$1
	n=$(md5sum <<< "$str")
	echo $((0x${n%% *}))
}
